server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://34.64.218.29:3306/meetty_db
    username: ${PROD_USERNAME}
    password: ${PROD_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  jwt:
    secure-cookie: true

app:
  base-url: http://34.64.218.29:8080

logging:
  level:
    root: WARN           # 전체 기본 로그 레벨을 WARN으로 줄임
    org.springframework: WARN    # Spring 관련 로그도 최소화
    org.hibernate.SQL: ERROR    # Hibernate SQL 로그 제거
    com.example.meetty: INFO    # (선택) 내 코드만 INFO로 보고 싶을 때