server:
    port: 8080

spring:
    jwt:
        secret: ${JWT_SECRET}
        token:
            access-expiration-time: 43200000
            refresh-expiration-time: 604800000

    data:
        redis:
            host: localhost
            port: 6379

    mail:
        host: smtp.gmail.com
        port: 587
        username: violetcarrot21@gmail.com
        password: uhrk bhbx mvum raox
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.debug: true

    config:
        import:
            - application-oauth2.yml

    cloud:
        gcp:
            project-id: mystic-centaur-458406-v1
            credentials:
                location: classpath:GCP/gcp-service-key.json

gcp:
    storage:
        bucket: meetty-img

app:
    base-url: http://localhost:8080